### ISSUE TITLE
Configure with package.json?

### ISSUE THREAD

**Issue by glitchesnetwork** [pluma0/moduleify#2]
I'm using package.json to configure my browserify-shim, browserify-swap, and browserify transform properties. I tried various ways to configure moduleify to in my package.json using the same ways I put in my other transform configurations and it didn't work. Thank you!

**Comment by pluma** [comment]
I'm amazed it still works with the current version of browserify, actually.

It's probably easiest to just port the transform to [browserify-transform-tools](https://www.npmjs.com/package/browserify-transform-tools) like the other transforms I maintain. I'll try to get to it ASAP.

**Comment by pluma** [comment]
Sorry.
